// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type PrStatus string

const (
	PrStatusOPEN   PrStatus = "OPEN"
	PrStatusMERGED PrStatus = "MERGED"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus
	Valid    bool // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PullRequest struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
	Status          PrStatus
	CreatedAt       sql.NullTime
	MergedAt        sql.NullTime
}

type PullRequestReviewer struct {
	PullRequestID string
	UserID        string
}

type Team struct {
	TeamName string
}

type User struct {
	UserID   string
	Username string
	TeamName sql.NullString
	IsActive bool
}
