// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pull_requests.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPR = `-- name: GetPR :one
SELECT pull_request_id, pull_request_name, author_id, status, created_at, merged_at
FROM pull_requests
WHERE pull_request_id = $1
`

func (q *Queries) GetPR(ctx context.Context, pullRequestID uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPR, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const insertPR = `-- name: InsertPR :exec
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id, status)
VALUES ($1,$2,$3,'OPEN')
`

type InsertPRParams struct {
	PullRequestID   uuid.UUID
	PullRequestName string
	AuthorID        uuid.UUID
}

func (q *Queries) InsertPR(ctx context.Context, arg InsertPRParams) error {
	_, err := q.db.ExecContext(ctx, insertPR, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	return err
}

const setPRMerged = `-- name: SetPRMerged :one
UPDATE pull_requests
SET status='MERGED', merged_at = now()
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

func (q *Queries) SetPRMerged(ctx context.Context, pullRequestID uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, setPRMerged, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}
