// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pull_request_reviewers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addReviewer = `-- name: AddReviewer :exec
INSERT INTO pull_request_reviewers (pull_request_id, user_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddReviewerParams struct {
	PullRequestID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) AddReviewer(ctx context.Context, arg AddReviewerParams) error {
	_, err := q.db.ExecContext(ctx, addReviewer, arg.PullRequestID, arg.UserID)
	return err
}

const getPRReviewers = `-- name: GetPRReviewers :many
SELECT u.user_id FROM users u
JOIN pull_request_reviewers r ON u.user_id = r.user_id
WHERE r.pull_request_id = $1
ORDER BY u.user_id
`

func (q *Queries) GetPRReviewers(ctx context.Context, pullRequestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getPRReviewers, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRsForReviewer = `-- name: GetPRsForReviewer :many
SELECT p.pull_request_id, p.pull_request_name, p.author_id, p.status
FROM pull_requests p
JOIN pull_request_reviewers r ON p.pull_request_id = r.pull_request_id
WHERE r.user_id = $1
ORDER BY p.created_at DESC
`

type GetPRsForReviewerRow struct {
	PullRequestID   uuid.UUID
	PullRequestName string
	AuthorID        uuid.UUID
	Status          PrStatus
}

func (q *Queries) GetPRsForReviewer(ctx context.Context, userID uuid.UUID) ([]GetPRsForReviewerRow, error) {
	rows, err := q.db.QueryContext(ctx, getPRsForReviewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPRsForReviewerRow
	for rows.Next() {
		var i GetPRsForReviewerRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceReviewer = `-- name: ReplaceReviewer :exec
DELETE FROM pull_request_reviewers
WHERE pull_request_id = $1 AND user_id = $2
`

type ReplaceReviewerParams struct {
	PullRequestID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error {
	_, err := q.db.ExecContext(ctx, replaceReviewer, arg.PullRequestID, arg.UserID)
	return err
}
