// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pull_requests.sql

package database

import (
	"context"
	"database/sql"
)

const createPR = `-- name: CreatePR :exec
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id, status, created_at)
VALUES ($1,$2,$3,'OPEN', NOW())
`

type CreatePRParams struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
}

func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) error {
	_, err := q.db.ExecContext(ctx, createPR, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	return err
}

const getActiveReviewersForTeam = `-- name: GetActiveReviewersForTeam :many
SELECT user_id
FROM users
WHERE team_name = $1
AND is_active = TRUE
AND user_id <> $2
`

type GetActiveReviewersForTeamParams struct {
	TeamName sql.NullString
	UserID   string
}

func (q *Queries) GetActiveReviewersForTeam(ctx context.Context, arg GetActiveReviewersForTeamParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveReviewersForTeam, arg.TeamName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEligibleReassignReviewers = `-- name: GetEligibleReassignReviewers :many
SELECT u.user_id
FROM users u
WHERE u.team_name = $1
  AND u.is_active = TRUE
  AND u.user_id <> $2
  AND u.user_id NOT IN (
      SELECT prr.user_id
      FROM pull_request_reviewers prr
      WHERE prr.pull_request_id = $3
  )
`

type GetEligibleReassignReviewersParams struct {
	TeamName      sql.NullString
	UserID        string
	PullRequestID string
}

func (q *Queries) GetEligibleReassignReviewers(ctx context.Context, arg GetEligibleReassignReviewersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEligibleReassignReviewers, arg.TeamName, arg.UserID, arg.PullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPR = `-- name: GetPR :one
SELECT pull_request_id, pull_request_name, author_id, status, created_at, merged_at
FROM pull_requests
WHERE pull_request_id = $1
`

func (q *Queries) GetPR(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPR, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const isMerged = `-- name: IsMerged :one
SELECT COUNT(*) > 0
FROM pull_requests
WHERE pull_request_id = $1 AND status ='MERGED'
`

func (q *Queries) IsMerged(ctx context.Context, pullRequestID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMerged, pullRequestID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setPRMerged = `-- name: SetPRMerged :one
UPDATE pull_requests
SET status='MERGED', merged_at = now()
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

func (q *Queries) SetPRMerged(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, setPRMerged, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}
