// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats.sql

package database

import (
	"context"
)

const getAssignmentStats = `-- name: GetAssignmentStats :many
SELECT user_id, COUNT(*) AS count
FROM pull_request_reviewers
GROUP BY user_id
`

type GetAssignmentStatsRow struct {
	UserID string
	Count  int64
}

func (q *Queries) GetAssignmentStats(ctx context.Context) ([]GetAssignmentStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentStatsRow
	for rows.Next() {
		var i GetAssignmentStatsRow
		if err := rows.Scan(&i.UserID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRStats = `-- name: GetPRStats :many
SELECT status, COUNT(*) AS count
FROM pull_requests
GROUP BY status
`

type GetPRStatsRow struct {
	Status PrStatus
	Count  int64
}

func (q *Queries) GetPRStats(ctx context.Context) ([]GetPRStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPRStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPRStatsRow
	for rows.Next() {
		var i GetPRStatsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
